addons:
  ssh_known_hosts: fuzzyvagina@robert-treat-paine.dreamhost.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_edb3b338d255_key -iv $encrypted_edb3b338d255_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build fuzzyvagina@robert-treat-paine.dreamhost.com:_tmp && cat script/deploy.sh | ssh -tt fuzzyvagina@robert-treat-paine.dreamhost.com
  on:
    branch: master